[project]
name = "backup-sidechain"
authors = ["Decentralized Infrastructure Team"]
description = "A secure backup and recovery mechanism for cross-chain data synchronization"
telemetry = false
requirements = []
[contracts.backup-sidechain]
path = "contracts/backup-sidechain.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
